### ISSUE TITLE
LGPLv3/other relicense?

### ISSUE THREAD

**Issue by shinyquagsire23** [clone2727/smushplay#3]
My JKDF2+MoTS decompilation project (https://github.com/shinyquagsire23/OpenJKDF2) reached a milestone where MoTS can be completed in its entirety now, and one of my remaining TODO items is cutscene codecs. For JKDF2 I used libsmacker, but it seems there are not any other Smush codecs out there and in general I'd like to pick something that I could upstream to and help other projects (as opposed to decompiling LEC's codec code).

The issue is that OpenJKDF2, being a derivative work of the original game, is basically stuck on a 1-clause BSD license (anything using OpenJKDF2 has to acknowledge that it's © LEC first and foremost). GPLv3 considers even dynamically linking to be a derivative work, and that copyright requirement would violate GPL.

LGPLv3 would maintain copyleft and allow me to include a smushplay.dll that gets linked at runtime.

Something like Mozilla would maintain copyleft and allow statically linking I believe.

**Comment by shinyquagsire23** [comment]
Ahh wait, if it was based on ScummVM code then it might be stuck on GPLv3 unless rewritten.

**Comment by clone2727** [comment]
It's based on ScummVM (GPLv2+), but then my additions are GPLv3+. I'm not relicensing it to LGPL or MPL.

**Comment by clone2727** [comment]
(At least you can use ffmpeg -- which is LGPL -- as a starting ground for SMUSH and RE codec 48 if necessary -- it's not too dissimilar from codec47 anyway.)
